accounts/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login_history/', views.login_history, name='login_history'),
    path('security_log/', views.security_log, name='security_log')
]

inventory/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views


app_name = 'inventory'
urlpatterns = [
    path(
        'device_inventory_list/',
        login_required(views.device_inventory_list),
        name='device_inventory_list'
    ),
    path(
        'device_detailed_information/<device_id>/',
        login_required(views.device_detailed_information),
        name='device_detailed_information'
    ),
    path(
        'device_force_rediscovery/<device_id>/',
        login_required(views.device_force_rediscovery),
        name='device_force_rediscovery'
    ),
    path(
        'device_inventory_edit/<device_id>/',
        login_required(views.device_inventory_edit),
        name='device_inventory_edit'
    ),
    path(
        'device_interface_edit/<interface_name>/',
        login_required(views.device_interface_edit),
        name='device_interface_edit'
    ),
    path(
        'device_interface_delete/<interface_name>/',
        login_required(views.device_interface_delete),
        name='device_interface_delete'
    ),
    path(
        'device_inventory_import/',
        login_required(views.device_inventory_import),
        name='device_inventory_import'
    ),
    path(
        'device_inventory_create/',
        login_required(views.device_inventory_create),
        name='device_inventory_create'
    ),
    path(
        'device_inventory_delete/<device_id>/',
        login_required(views.device_inventory_delete),
        name='device_inventory_delete'
    ),
    path(
        'device_run_command',
        login_required(views.device_run_command),
        name='device_run_command'
    )
]

net_autom8/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.contrib.auth.decorators import login_required, permission_required


urlpatterns = [
    path('dashboard/', include('dashboard.urls')),
    path('inventory/', include('inventory.urls')),
    path('housekeeping/', include('housekeeping.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path(
        '',
        login_required(
            TemplateView.as_view(template_name='registration/profile.html')
        ),
        name='profile'
    )
]

inventory/models.py
from django.db import models
from django.utils import timezone


class Device(models.Model):
    hostname = models.CharField(unique=True, max_length=255)
    mgmt_ip = models.GenericIPAddressField(unique=True, max_length=12)
    username = models.CharField(blank=True, null=True, max_length=255)
    password = models.CharField(blank=True, null=True, max_length=255)
    software_version = models.CharField(blank=True, null=True, max_length=255)
    serial_number = models.CharField(blank=True, null=True, max_length=255)
    vendor = models.CharField(max_length=255)
    description = models.CharField(blank=True, null=True, max_length=255)
    hardware_model = models.CharField(blank=True, null=True, max_length=255)
    rest_conf_enabled = models.BooleanField(blank=True, null=True)
    device_uptime = models.CharField(blank=True, null=True, max_length=255)
    last_polled = models.DateTimeField(blank=True, null=True)
    date_added = models.DateTimeField(default=timezone.now())


class DeviceInterfaces(models.Model):
    device_id = models.ForeignKey(Device, null=True, on_delete=models.CASCADE)
    name = models.CharField(blank=True, null=True, max_length=255)
    interface_type = models.CharField(blank=True, null=True, max_length=255)
    description = models.CharField(blank=True, null=True, max_length=255)
    ipv4_address = models.GenericIPAddressField(
        blank=True, null=True, max_length=12)
    ipv4_subnet_mask = models.CharField(blank=True, null=True, max_length=12)
    admin_status = models.CharField(blank=True, null=True, max_length=255)
    oper_status = models.CharField(blank=True, null=True, max_length=255)
    phys_address = models.CharField(blank=True, null=True, max_length=255)

inventory/forms.py
from django import forms
from django.core.validators import FileExtensionValidator
from django.utils.html import mark_safe
from .models import Device, DeviceInterfaces


VENDORS = (
    ('', '--- Select ---'),
    ('Cisco', 'Cisco'),
    ('Juniper', 'Juniper'),
    ('Nokia', 'Nokia'),
)

INTERFACE_STATES = (
    ('', '--- Select ---'),
    ('up', 'up'),
    ('down', 'down')
)


class UploadFileForm(forms.Form):
    file = forms.FileField(
        label='',
        widget=forms.FileInput(
            attrs={'class': 'form-control form-control-sm'}
        ),
        required=False,
        validators=[FileExtensionValidator(allowed_extensions=['csv'])]
    )


class DeviceCreateForm(forms.Form):
    hostname = forms.CharField(
        label=mark_safe('<i class="fas fa-signature"></i> Hostname'),
        widget=forms.TextInput(attrs={'class': 'form-control form-control-sm'})
    )
    mgmt_ip = forms.CharField(
        label=mark_safe('<i class="fas fa-at"></i> MGMT IP'),
        widget=forms.TextInput(attrs={'class': 'form-control form-control-sm'})
    )
    vendor = forms.ChoiceField(
        label=mark_safe('<i class="fas fa-briefcase"></i> Vendor'),
        widget=forms.Select(attrs={'class': 'form-control form-select-sm'}),
        choices=VENDORS
    )
    username = forms.CharField(
        label=mark_safe('<i class="fas fa-users-cog"></i> Username'),
        widget=forms.TextInput(
            attrs={'class': 'form-control form-control-sm',
                   'placeholder': 'Optional field'}
        ),
        required=False
    )
    password = forms.CharField(
        label=mark_safe('<i class="fas fa-key"></i> Password'),
        widget=forms.PasswordInput(
            attrs={'class': 'form-control form-control-sm',
                   'placeholder': 'Optional field'}
        ),
        required=False
    )


class DeviceEditForm(forms.ModelForm):
    class Meta:
        model = Device
        fields = ('hostname', 'mgmt_ip', 'username', 'password')
        labels = {
            'hostname': mark_safe('<i class="fas fa-signature"></i> Hostname'),
            'mgmt_ip': mark_safe('<i class="fas fa-at"></i> MGMT IP'),
            'username': mark_safe('<i class="fas fa-users-cog"></i> Username'),
            'password': mark_safe('<i class="fas fa-key"></i> Password')

        }
        widgets = {
            'hostname': forms.TextInput(attrs={'class': 'form-control form-control-sm'}),
            'mgmt_ip': forms.TextInput(attrs={'class': 'form-control form-control-sm'}),
            'username': forms.TextInput(attrs={'class': 'form-control form-control-sm'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control form-control-sm'})
        }


class InterfaceEditForm(forms.ModelForm):
    class Meta:
        model = DeviceInterfaces
        fields = (
            'description',
            'ipv4_address',
            'ipv4_subnet_mask',
            'admin_status'
        )
        labels = {
            'description': mark_safe('<i class="fas fa-sign"></i> Description'),
            'ipv4_address': mark_safe('<i class="fas fa-at"></i> IP Address'),
            'ipv4_subnet_mask': mark_safe('<i class="fas fa-mask"></i> Subnet Mask'),
            'admin_status': mark_safe('<i class="fas fa-check-circle"></i> Admin Status')
        }
        widgets = {
            'description': forms.TextInput(attrs={'class': 'form-control form-control-sm'}),
            'ipv4_address': forms.TextInput(attrs={'class': 'form-control form-control-sm'}),
            'ipv4_subnet_mask': forms.TextInput(attrs={'class': 'form-control form-control-sm'}),
            'admin_status': forms.Select(attrs={'class': 'form-control form-select-sm'}, choices=INTERFACE_STATES)
        }

inventory/views.py
# Pandas
import pandas as pd
# Django
from django.shortcuts import render
from django.contrib import messages
from django.http import JsonResponse, HttpRequest
from django.http.response import HttpResponseRedirect
from django.utils import timezone
# Other
from random import randint
# Tasks
from tasks.tasks import task_run_device_discovery
from tasks.tasks import task_run_device_rediscovery
# Scripts
from tasks.scripts.device_configurator import edit_interface, delete_interface
from tasks.scripts.device_run_cmd import cli_command_runner
# Models
from .models import Device, DeviceInterfaces
from housekeeping.models import CeleryUserJobResults
# Forms
from .forms import UploadFileForm, DeviceCreateForm, DeviceEditForm, InterfaceEditForm


def inventory_importer(file):
    try:
        data = []
        add_random_number = randint(100, 1000)
        uploaded_file = f'uploaded_files/imported_file_{add_random_number}.csv'
        with open(uploaded_file, 'wb+') as csv_file:
            for chunk in file.chunks():
                csv_file.write(chunk)
        df = pd.read_csv(uploaded_file, sep=',')
        for i in range(len(df)):
            data.append(
                Device(
                    hostname=df.iloc[i][0],
                    mgmt_ip=df.iloc[i][1],
                    vendor=df.iloc[i][2],
                    date_added=timezone.now()
                )
            )
        Device.objects.bulk_create(data)
        return {
            'status': 'success',
            'message': 'CSV file imported successfully!'
        }
    except Exception as error:
        return {
            'status': 'fail',
            'message': str(error)
        }


def device_detailed_information(request, device_id):
    device = Device.objects.get(pk=device_id)
    context = {
        'title': 'Device Detailed Information',
        'card_header': f'Information for: {device.hostname} {device.mgmt_ip}',
        'data': {
            'version': device,
            'interfaces': DeviceInterfaces.objects.filter(device_id=device_id)
        }
    }
    return render(
        request,
        'inventory/device_detailed_information.html',
        context
    )


def device_force_rediscovery(request, device_id):
    device = Device.objects.get(pk=device_id)
    task = task_run_device_rediscovery.delay(device_id)
    task_add_to_db = CeleryUserJobResults(
        task_id=task.id,
        task_requested_by=request.user,
        start_time=timezone.now()
    )
    task_add_to_db.save()
    messages.success(
        request,
        f'Rediscovery task added for {device.hostname}: {task.id}')
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def device_inventory_delete(request, device_id):
    device = Device.objects.get(pk=device_id)
    device.delete()
    messages.success(
        request,
        f'Device: {device.hostname} was deleted successfully!'
    )
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def device_inventory_create(request):
    form = DeviceCreateForm(request.POST)
    context = {
        'title': 'Inventory - Create Device',
        'card_header': 'Inventory - Create Device',
        'form': form
    }
    if request.method == 'GET':
        return render(
            request,
            'inventory/device_inventory_create.html',
            context
        )
    elif request.method == 'POST':
        if form.is_valid():
            try:
                add_device = Device(
                    hostname=request.POST['hostname'],
                    mgmt_ip=request.POST['mgmt_ip'],
                    username=request.POST['username'],
                    password=request.POST['password'],
                    vendor=request.POST['vendor'],
                    date_added=timezone.now()
                )
                add_device.save()
                task = task_run_device_discovery.delay()
                task_add_to_db = CeleryUserJobResults(
                    task_id=task.id,
                    task_requested_by=request.user,
                    start_time=timezone.now()
                )
                task_add_to_db.save()
                messages.success(
                    request,
                    f'Device added successfully! Pending discovery: {task.id}'
                )
            except Exception as error:
                messages.error(request, str(error))
        else:
            messages.error(
                request,
                'Invalid information provided!'
            )
        return HttpResponseRedirect(request.path)


def device_inventory_import(request):
    form = UploadFileForm(request.POST, request.FILES)
    context = {
        'title': 'Inventory - Import Devices',
        'card_header': 'Inventory - Import Devices',
        'form': form
    }
    if request.method == 'GET':
        return render(
            request,
            'inventory/device_inventory_import.html',
            context
        )
    if request.method == 'POST':
        if request.FILES:
            if form.is_valid():
                result = inventory_importer(request.FILES['file'])
                if result['status'] == 'success':
                    task = task_run_device_discovery.delay()
                    task_add_to_db = CeleryUserJobResults(
                        task_id=task.id,
                        task_requested_by=request.user,
                        start_time=timezone.now()
                    )
                    task_add_to_db.save()
                    messages.success(
                        request,
                        f'Import was successful! Pending discovery: {task.id}')
                else:
                    messages.error(request, result)
            else:
                return render(
                    request,
                    'inventory/device_inventory_import.html',
                    context
                )
        else:
            messages.error(request, 'No file was provided!')
        return HttpResponseRedirect(request.path)


def device_inventory_edit(request, device_id):
    device = Device.objects.get(pk=device_id)
    context = {
        'title': 'Inventory - Device Editor',
        'card_header': f'Device Editor: {device.hostname} {device.mgmt_ip}',
        'data': device
    }
    if request.method == 'GET':
        form = DeviceEditForm(instance=device)
        context['form'] = form
        return render(request, 'inventory/device_inventory_edit.html', context)
    elif request.method == 'POST':
        form = DeviceEditForm(request.POST, instance=device)
        context['form'] = form
        if form.is_valid():
            form.save()
            messages.success(
                request,
                f'Changes to: {device.hostname} succeeded!'
            )
        else:
            messages.error(
                request,
                'There has been a problem editing the device!'
            )
        return HttpResponseRedirect(request.path)


def device_interface_delete(request, interface_name):
    interface = DeviceInterfaces.objects.get(name=interface_name)
    interface.delete()
    delete_interface(interface.device_id, interface)
    messages.success(
        request,
        f'Interface: {interface.name} was deleted successfully!'
    )
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def device_interface_edit(request, interface_name):
    interface = DeviceInterfaces.objects.get(name=interface_name)
    context = {
        'title': 'Device - Edit Interface',
        'card_header': f'Device: {interface.device_id.hostname} - Editing Interface: {interface.name}'
    }
    if request.method == 'GET':
        form = InterfaceEditForm(instance=interface)
        context['form'] = form
        return render(request, 'inventory/device_interface_edit.html', context)
    elif request.method == 'POST':
        form = InterfaceEditForm(request.POST, instance=interface)
        context['form'] = form
        if form.is_valid():
            edit_interface(interface.device_id, interface)
            form.save()
            messages.success(
                request,
                f'Changes to: {interface.name} succeeded!'
            )
        else:
            messages.error(
                request,
                'There has been a problem editing the interface!'
            )
        return HttpResponseRedirect(request.path)
    return render(request, 'inventory/device_interface_edit.html', context)


def device_inventory_list(request):
    list_of_devices = Device.objects.all()
    context = {
        'title': 'Inventory - List Devices',
        'card_header': 'Inventory - List Devices',
        'data': list_of_devices,
    }
    return render(request, 'inventory/device_inventory_list.html', context)


def device_run_command(request):
    if request.method == 'POST':
        post_data = request.POST.get('run_show_command')
        device_id = post_data.split(':')[0]
        command_id = post_data.split(':')[1]
        commands = {
            '1': 'show ip interface brief',
            '2': 'show interfaces description',
            '3': 'show ip arp',
            '4': 'show ip route',
            '5': 'show ip cef',
            '6': 'show version'
        }
        command = commands.get(command_id)
        output = cli_command_runner(device_id, command)
        if output['status'] == 'success':
            return JsonResponse(
                {
                    'items': output['details']
                },
                json_dumps_params={'indent': 4}
            )
        else:
            return 'Unable to get output from device...'

templates/inventory/device_create.html
{% extends "base_template/base.html"%}
{% load crispy_forms_tags %}
{% block content %}
<form method="POST">
{% csrf_token %}
<div class="col-md-3">
    {{ form|crispy }}
</div>
<button type="submit" class="btn btn-sm btn-primary">
    <i class="fas fa-plus-circle"></i>
    Add Device
</button>
</form>
{% endblock %}

templates/inventory/device_detailed_information.html
{% extends "base_template/base.html"%}
{% load static %}
{% block content %}
<div class="row">
    <div class="col-md-4">
        <div class="card">
            <div class="card-body">
                <ul class="list-group">
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        HW Model:
                        <span class="badge bg-primary" style="width: 150px">{{ data.version.hardware_model }}</span>
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        Serial:
                        <span class="badge bg-primary" style="width: 150px">{{ data.version.serial_number }}</span>
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        Software:
                        <span class="badge bg-primary" style="width: 150px">{{ data.version.software_version }}</span>
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        Uptime:
                        <span class="badge bg-primary" style="width: 150px">{{ data.version.device_uptime }}</span>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-md-8">
        <div class="card">
            <div class="card-body">
                <div class="table-responsive rounded">
                    <table id="InterfaceList" class="table table-sm table-hover table-borderless align-middle"
                        style="width:100%">
                        <thead>
                            <tr>
                                <th><i class="fas fa-ethernet"></i> Interface</th>
                                <th><i class="fas fa-sign"></i> Description</th>
                                <th><i class="fas fa-at"></i> IP</th>
                                <th><i class="fas fa-check-circle"></i> Status</th>
                                <th><i class="fas fa-random"></i> BIA</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for interface in data.interfaces %}
                            <tr>
                                <td>{{ interface.name }}</td>
                                {% if interface.description %}
                                <td>{{ interface.description }}</td>
                                {% else %}
                                <td>N/A</td>
                                {% endif %}
                                {% if interface.ipv4_address %}
                                <td>{{ interface.ipv4_address }}/{{ interface.ipv4_subnet_mask }}</td>
                                {% else %}
                                <td>0.0.0.0/0</td>
                                {% endif %}
                                {% if 'up' in interface.admin_status and 'up' in interface.oper_status %}
                                <td><i class="fas fa-check-double text-success blink"></i></td>
                                {% else %}
                                <td><i class="far fa-times-circle text-danger blink"></i></td>
                                {% endif %}
                                {% if interface.phys_address %}
                                <td>{{ interface.phys_address }} </td>
                                {% else %}
                                <td>N/A</td>
                                {% endif %}
                                <td>
                                    <a class="text-decoration-none"
                                        href="{% url 'inventory:device_interface_edit' interface.name %}"
                                        data-bs-toggle="tooltip" title="Edit">
                                        <i class="fas fa-edit text-info"></i>
                                    </a>
                                    {% if interface.interface_type != 'iana-if-type:ethernetCsmacd' %}
                                    <a class="text-decoration-none"
                                        href="{% url 'inventory:device_interface_delete' interface.name %}"
                                        data-bs-toggle="tooltip" title="Delete">
                                        <i class="fas fa-trash-alt text-danger"></i>
                                    </a>
                                    {% endif %}
                                </td>
                                {% endfor %}
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <form>
                {% csrf_token %}
                    <div class="input-group mb-3" hx-ext="client-side-templates">
                        <label class="input-group-text">Command</label>
                        <select class="form-select" name="run_show_command" id="run_show_command">
                            <option selected disabled>Choose...</option>
                            <option value="{{ data.version.id }}:1">show ip interface brief</option>
                            <option value="{{ data.version.id }}:2">show interfaces description</option>
                            <option value="{{ data.version.id }}:3">show ip arp</option>
                            <option value="{{ data.version.id }}:4">show ip route</option>
                            <option value="{{ data.version.id }}:5">show ip cef</option>
                            <option value="{{ data.version.id }}:6">show version</option>
                        </select>
                        <button type="button" class="btn btn-sm btn-success" hx-post="{% url 'inventory:device_run_command' %}" hx-target="#command_output" hx-indicator="#loader_bars" nunjucks-template="template_of_cmd_output">
                            <i class="fas fa-terminal"></i> Run
                        </button>
                    </div>
                </form>
                <div class="d-flex justify-content-center">
                    <img id="loader_bars" class="htmx-indicator" alt="Loading..." src="{% static 'images/loaders/bars.svg' %}"/>
                </div>
                <div id="command_output"></div>
                <template id="template_of_cmd_output">
                    {% verbatim %}
                        {% for item in items %}
                            {% for key, value in item %}
                                {{ value }}<br>
                            {% endfor %}
                        {% endfor %}
                    {% endverbatim %}
                </template>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/inventory/device_interface_edit.html
{% extends "base_template/base.html"%}
{% load crispy_forms_tags %}
{% block content %}
<form method="POST">
    {{ data.device_id }}
    {% csrf_token %}
    <div class="col-md-3">
        {{ form|crispy }}
    </div>
    <button type="submit" class="btn btn-sm btn-primary">
        <i class="fas fa-pencil-alt"></i>
        Amend
    </button>
</form>
{% endblock %}

templates/inventory/device_inventory_create.html
{% extends "base_template/base.html"%}
{% load crispy_forms_tags %}
{% block content %}
<div class="alert alert-info" role="alert">
  Please note, default credentials are:
  <kbd>developer / C1sco12345</kbd>
</div>
<form method="POST">
{% csrf_token %}
<div class="col-md-3">
    {{ form|crispy }}
</div>
<button type="submit" class="btn btn-sm btn-primary">
    <i class="fas fa-plus-circle"></i>
    Add Device
</button>
</form>
{% endblock %}

templates/inventory/device_inventory_edit.html
{% extends "base_template/base.html"%}
{% load crispy_forms_tags %}
{% block content %}
<form method="POST">
{% csrf_token %}
<div class="col-md-3">
    {{ form|crispy }}
</div>
<button type="submit" class="btn btn-sm btn-primary">
    <i class="fas fa-pencil-alt"></i>
    Amend
</button>
</form>
{% endblock %}

templates/inventory/device_inventory_import.html
{% extends "base_template/base.html"%}
{% load crispy_forms_tags %}
{% block content %}
<div class="alert alert-info pb-0" role="alert">
  <p class="lead text-dark">
    Please use the following header fields in the CSV file:
  </p>
  <p class="text-muted">
    "Hostname","IP","Vendor"
  </p>
</div>
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="col-md-2 mt-3 mb-3">
    {{ form|crispy }}
  </div>
  <button type="submit" class="btn btn-sm btn-primary">
    <i class="fas fa-file-upload"></i>
    Upload
  </button>
</form>
{% endblock %}

templates/inventory/device_inventory_list.html
{% extends "base_template/base.html"%}
{% block content %}
{% if data %}
<div class="table-responsive rounded">
    <table id="device_inventory" class="table table-hover table-sm" style="width:100%">
        <thead>
            <tr>
                <th><i class="fas fa-signature"></i> Hostname</th>
                <th><i class="fas fa-at"></i> IP</th>
                <th><i class="fas fa-briefcase"></i> Vendor</th>
                <th><i class="fas fa-sitemap"></i> Model</th>
                <th><i class="fas fa-code-branch"></i> Software</th>
                <th><i class="fas fa-barcode"></i> Serial Number</th>
                <th><i class="fas fa-keyboard"></i> Mgmt</th>
                <th><i class="fas fa-calendar-day"></i> Date Added</th>
                <th><i class="fas fa-poll"></i> Last Poll</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for device in data %}
            <tr>
                <td>
                    <a class="badge bg-primary text-decoration-none"
                        href="{% url 'inventory:device_detailed_information' device.id %}"
                        onclick="spinner_toggle_on();">
                        {{ device.hostname }}
                    </a>
                </td>
                <td>{{ device.mgmt_ip }}</td>
                <td>{{ device.vendor }}</td>
                <td>{{ device.hardware_model }}</td>
                <td>{{ device.software_version }}</td>
                <td>{{ device.serial_number }}</td>
                {% if device.rest_conf_enabled %}
                <td>
                    <badge class="badge bg-success" style="width:100px">
                        <i class="fas fa-terminal"></i> RESTCONF
                    </badge>
                </td>
                {% else %}
                <td>
                    <badge class="badge bg-secondary" style="width:100px">
                        <i class="fas fa-terminal"></i> SSH
                    </badge>
                </td>
                {% endif %}
                <td>{{ device.date_added }}</td>
                <td>{{ device.last_polled }}</td>
                <td>
                    <a class="text-decoration-none" href="{% url 'inventory:device_force_rediscovery' device.id %}"
                        data-bs-toggle="tooltip" title="Rediscover">
                        <i class="fas fa-sync-alt"></i>
                    </a>
                    <a class="text-decoration-none" href="{% url 'inventory:device_inventory_edit' device.id %}"
                        data-bs-toggle="tooltip" title="Edit">
                        <i class="fas fa-edit text-info"></i>
                    </a>
                    <a class="text-decoration-none" href="{% url 'inventory:device_inventory_delete' device.id %}"
                        data-bs-toggle="tooltip" title="Delete">
                        <i class="fas fa-trash-alt text-danger"></i>
                    </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% else %}
<h5 class="my-5 fw-bold text-center">No devices are currently present in the database...</h5>
{% endif %}
{% endblock %}
{% block javascript %}
<script>
    $(document).ready(function () {
        $('#device_inventory').DataTable(
            {
                renderer: 'bootstrap',
                select: false,
                fixedColumns: true,
                responsive: true,
                ordering: true,
                dom: '<"top"B>rt<"bottom"iflp><"clear">',
                lengthMenu: [10, 15, 20],
                buttons: [
                    {
                        'extend': 'copy',
                        'text': 'Copy',
                        'className': 'btn btn-xs btn-outline-dark'
                    },
                    {
                        'extend': 'csv',
                        'text': 'CSV',
                        'className': 'btn btn-xs btn-outline-dark'
                    },
                    {
                        'extend': 'excel',
                        'text': 'MS Excel',
                        'className': 'btn btn-xs btn-outline-dark'
                    },
                    {
                        'extend': 'pdf',
                        'text': 'PDF',
                        'className': 'btn btn-xs btn-outline-dark'
                    }
                ]
            }
        );
    });
</script>
{% endblock javascript %}