accounts/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login_history/', views.login_history, name='login_history'),
    path('security_log/', views.security_log, name='security_log')
]

dashboard/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views


app_name = 'dashboard'
urlpatterns = [
    path('', login_required(views.dashboard), name='dashboard')
]

housekeeping/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views


app_name = 'housekeeping'
urlpatterns = [
    path(
        '',
        login_required(views.housekeeping_celery_user_tasks),
        name='housekeeping_celery_user_tasks'
    ),
    path(
        'housekeeping_celery_backend_tasks/',
        login_required(views.housekeeping_celery_backend_tasks),
        name='housekeeping_celery_backend_tasks'
    )
]

inventory/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views


app_name = 'inventory'
urlpatterns = [
    path(
        'device_inventory_list/',
        login_required(views.device_inventory_list),
        name='device_inventory_list'
    ),
    path(
        'device_detailed_information/<device_id>/',
        login_required(views.device_detailed_information),
        name='device_detailed_information'
    ),
    path(
        'device_force_rediscovery/<device_id>/',
        login_required(views.device_force_rediscovery),
        name='device_force_rediscovery'
    ),
    path(
        'device_inventory_edit/<device_id>/',
        login_required(views.device_inventory_edit),
        name='device_inventory_edit'
    ),
    path(
        'device_interface_edit/<interface_name>/',
        login_required(views.device_interface_edit),
        name='device_interface_edit'
    ),
    path(
        'device_interface_delete/<interface_name>/',
        login_required(views.device_interface_delete),
        name='device_interface_delete'
    ),
    path(
        'device_inventory_import/',
        login_required(views.device_inventory_import),
        name='device_inventory_import'
    ),
    path(
        'device_inventory_create/',
        login_required(views.device_inventory_create),
        name='device_inventory_create'
    ),
    path(
        'device_inventory_delete/<device_id>/',
        login_required(views.device_inventory_delete),
        name='device_inventory_delete'
    ),
    path(
        'device_run_command',
        login_required(views.device_run_command),
        name='device_run_command'
    )
]

net_autom8/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.contrib.auth.decorators import login_required, permission_required


urlpatterns = [
    path('dashboard/', include('dashboard.urls')),
    path('inventory/', include('inventory.urls')),
    path('housekeeping/', include('housekeeping.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path(
        '',
        login_required(
            TemplateView.as_view(template_name='registration/profile.html')
        ),
        name='profile'
    )
]

templates/navbar/navbar.html
{% load static %}
{% if user.is_authenticated %}
<nav class="navbar navbar-expand-md navbar-light bg-light fixed-top border-bottom border-secondary shadow">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <i class="fas fa-robot fa-2x"></i>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item">
          <a class="nav-link text-dark" href="{% url 'dashboard:dashboard' %}" onclick="spinner_toggle_on()">
            <i class="fas fa-tachometer-alt"></i>
            Dashboard
          </a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle text-dark" href="#" id="HousekeepingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="fas fa-quidditch"></i>
            Housekeeping
          </a>
          <ul class="dropdown-menu" aria-labelledby="HousekeepingDropdown">
            <li><a class="dropdown-item" href="{% url 'housekeeping:housekeeping_celery_user_tasks' %}" onclick="spinner_toggle_on()">
                <i class="fas fa-users-cog"></i>
                User Tasks</a>
            </li>
            <li><a class="dropdown-item" href="{% url 'housekeeping:housekeeping_celery_backend_tasks' %}" onclick="spinner_toggle_on()">
                <i class="fas fa-cogs"></i>
                Backend Tasks</a>
            </li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle text-dark" href="#" id="InventoryDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="fas fa-boxes"></i>
            Inventory
          </a>
          <ul class="dropdown-menu" aria-labelledby="InventoryDropdown">
            <li><a class="dropdown-item" href="{% url 'inventory:device_inventory_list' %}" onclick="spinner_toggle_on()">
                <i class="fas fa-list-ul"></i>
                Device List</a>
            </li>
            <li><a class="dropdown-item" href="{% url 'inventory:device_inventory_create' %}">
                <i class="fas fa-plus-circle"></i>
                Add Device</a></li>
            <li><a class="dropdown-item" href="{% url 'inventory:device_inventory_import' %}">
                <i class="fas fa-file-import"></i>
                Import Devices</a>
            </li>
          </ul>
        </li>
      </ul>
      <div class="dropdown">
        <a class="btn btn-md btn-secondary dropdown-toggle" href="#" role="button" id="UserProfileDropdown" data-bs-toggle="dropdown" aria-expanded="false">
          <i class="fas fa-user-circle"></i>
          {{ user.username }}
        </a>
        <ul class="dropdown-menu" aria-labelledby="UserProfileDropdown">
          <li>
            <a class="dropdown-item" href="{% url 'profile' %}">
              <i class="fas fa-id-card-alt"></i> Profile
            </a>
          </li>
          <li>
            <a class="dropdown-item" href="{% url 'login_history' %}" onclick="spinner_toggle_on()">
              <i class="fas fa-history"></i> Logs
            </a>
          </li>
          <li>
            <a class="dropdown-item" href="{% url 'security_log' %}" onclick="spinner_toggle_on()">
              <i class="fas fa-shield-alt"></i> Security
            </a>
          </li>
          <li>
            <a class="dropdown-item" href="{% url 'logout' %}">
              <i class="fas fa-sign-out-alt"></i> Logout
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</nav>
{% endif %}